GET http://localhost:3000/publishers

###

GET http://localhost:3000/authors/6247df42ec6aa26370d0d94c



###

GET http://localhost:3000/books/detail/6247e476debd45aac3c20ba6


###


POST http://localhost:3000/books/new
Content-Type: application/json

{
    "id": 1,
    "name": "Cum zone"
}

###

DELETE http://localhost:3000/books/6238543d32a4eaf869f4879d


###


GET http://localhost:3000/db