GET http://localhost:3000/publishers

###

POST http://localhost:3000/books/new
Content-Type: application/json

{
    "id": 1,
    "name": "Cum zone"
}

###

DELETE http://localhost:3000/books/6238543d32a4eaf869f4879d