GET http://localhost:3000/api?title=how

###

PUT   http://localhost:3000/api/user/update-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyNjU2YTM2NjQ3NmMxNzMyMjgyN2RiZCIsInVzZXJuYW1lIjoid2lyZXhpYSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY1MTkwOTc2OH0.Y45iUtyAe0bautLXh6rQwmsHCS3TiWvCn4avI_pP2ec

{
    "address": 
        {
            "location": "458/3F Đ.Nguyễn Hữu Thọ, Tân Hưng, Quận 7, Thành phố Hồ Chí Minh, Vietnam",
             "type": "Home Sky"
        },
    "pos": "6275fac83bf11ada09d86272"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json


{
    "username": "wirexia",
    "password": "123456"
}

###


GET http://localhost:3000/api/user/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyNjU2YTM2NjQ3NmMxNzMyMjgyN2RiZCIsInVzZXJuYW1lIjoid2lyZXhpYSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY1MTgxMjg2OH0.DSAtjbTVYRLgHa9UxHy09SpjRIhwfkmn67huC1P8GSQ


###


POST http://localhost:3000/api/order/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyNjU2YTM2NjQ3NmMxNzMyMjgyN2RiZCIsInVzZXJuYW1lIjoid2lyZXhpYSIsInJvbGUiOiJ1c2VyIn0sImlhdCI6MTY1MTgxMjg2OH0.DSAtjbTVYRLgHa9UxHy09SpjRIhwfkmn67huC1P8GSQ

{
    "products": [
    {
        "productDetail": "6273708d03dc9df56e0033dc",
        "quantity": 1,
        "price": 538.400
    }, 
    {
        "productDetail": "6273708d03dc9df56e0033dd",
        "quantity": 1,
        "price": 502.200
    }]
}

###

DELETE http://localhost:3000/books/6238543d32a4eaf869f4879d


###


GET http://localhost:3000/db